[package]
name = "subcrate-example"
description = "Subcrate example"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false

